name: Gingersnap db-syncer - Build and publish

#on:
#  workflow_dispatch:
#    inputs:
#      ref:
#        description: "The db-syncer branch/tag to checkout when creating the image."
#        required: true
#        default: "test_pipeline"

on: 
  push:
    tags:
      - 'v*'
      
env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}   

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} 


      #- name: Tag the release
      #  run: |
      #    ls -la
      #    tree
      #    git tag -a v${{ env.release-version}} -m "Release db-syncer:: ${{ env.release-version}}"
      #    git push origin --tags

      - name: Checkout latest tag
        id: latesttag
        run: | 
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`) 
          git checkout $LATEST_TAG
          echo $LATEST_TAG >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: mvn package -DskipTests
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.PRIVATE_QUAY_USERNAME }}
          password: ${{ secrets.PRIVATE_QUAY_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          push: true
          tags: quay.io/pminz/db-syncer:${{ steps.latesttag.outputs.LATEST_TAG }}
          build-args: |
            OPERATOR_VERSION=${{ steps.latesttag.outputs.LATEST_TAG }}
