name: db-syncer -Create Tag

on:
  workflow_call:
    inputs:
      ref:
        type: string 
        default: "release_pipeline"
      repo:
        type: string
        default: gingersnap/db-syncer
         
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  
  release-version: ${{ github.event.inputs.ref }}

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.ref }} 
          repository: ${{ inputs.repo }}
          
      - name: Debug
        run: |
         echo "Workflow was triggered successfully"

      