name: db-syncer -Create Tag

on:
  workflow_call:
    inputs:
      ref:
        description: "The branch to checkout when creating the image."
        required: true
        default: "release_pipeline"
      
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  
  release-version: ${{ github.event.inputs.ref }}

jobs:
  tag:
    uses: pminz/db-syncer/.github/workflows/test_another_workflow.yaml@workflow_call
    with: 
      ref: ${{ github.event.inputs.ref }} 

         