name: db-syncer -Create Tag

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: "release_pipeline"
      
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  

jobs:
  tag:
    uses: pminz/db-syncer/.github/workflows/test_another_workflow.yaml@workflow_call
    with: 
      ref: ${{ github.event.inputs.ref }} 


         